In [2]:
import pandas as pd

In [3]:
human_part = pd.read_csv("db_3_human.csv", delimiter='\t')
mouse_part = pd.read_csv("general_bd_with_mp.tsv", delimiter='\t')

In [4]:
human_part

,Unnamed: 0.1,Unnamed: 0,gene_human,entrez_id_human,gene_mouse,MGI,MP,HPO-Term-ID,HPO-Term-Name
0,0,0,A1BG,1,A1bg,MGI:2152878,NaN,NaN,NaN
1,1,1,A1CF,29974,A1cf,MGI:1917115,"MP:0005367, MP:0005369, MP:0005370, MP:0005376...",NaN,NaN
2,2,2,A2M,2,A2m,MGI:2449119,NaN,NaN,NaN
3,3,3,A3GALT2,127550,A3galt2,MGI:2685279,NaN,NaN,NaN
4,4,4,A4GALT,53947,A4galt,MGI:3512453,"MP:0005376, MP:0005386, MP:0010768","HP:0000006, HP:0010970","Autosomal dominant inheritance, Blood group an..."
...,...,...,...,...,...,...,...,...,...
29681,29681,29681,ZYG11A,440590,Zyg11a,MGI:2446208,NaN,NaN,NaN
29682,29682,29682,ZYG11B,79699,Zyg11b,MGI:2685277,"MP:0005386, MP:0010768",NaN,NaN
29683,29683,29683,ZYX,7791,Zyx,MGI:103072,MP:0005384,NaN,NaN
29684,29684,29684,ZZEF1,23140,Zzef1,MGI:2444286,"MP:0005367, MP:0005378, MP:0005386, MP:0005390...",NaN,NaN
29685,29685,29685,ZZZ3,26009,Zzz3,MGI:1920453,NaN,NaN,NaN

In [5]:
mouse_part

,Unnamed: 0,MGI,MP
0,0,MGI:3608325,"MP:0005377,MP:0003631,MP:0005384"
1,1,MGI:1338010,"MP:0005377,MP:0005382,MP:0003384,MP:0002006,MP..."
2,2,MGI:1858964,NaN
3,3,MGI:1913363,MP:0005376
4,4,MGI:2681842,MP:0003631
...,...,...,...
20217,20217,MGI:1195966,"MP:0005386,MP:0003631"
20218,20218,MGI:107738,"MP:0005386,MP:0005389"
20219,20219,MGI:3052806,NaN
20220,20220,MGI:5594219,NaN
20221,20221,MGI:1336168,"MP:0010768,MP:0005376,MP:0005384"

In [6]:
check_mouse_pheno = pd.merge(human_part, mouse_part, on="MGI", how="left")
check_mouse_pheno = check_mouse_pheno[["MGI", "MP_x", "MP_y"]]

In [7]:
check_mouse_pheno["len_x"] = check_mouse_pheno.MP_x.apply(lambda x: len(str(x).split(", ")))
check_mouse_pheno["len_y"] = check_mouse_pheno.MP_y.apply(lambda x: len(str(x).split(",")))

In [8]:
check_mouse_pheno["different"] = check_mouse_pheno.len_x > check_mouse_pheno.len_y

In [9]:
check_mouse_pheno[check_mouse_pheno.different == True]

Empty DataFrame
Columns: [MGI, MP_x, MP_y, len_x, len_y, different]
Index: []

In [16]:
merged_hum_mouse = pd.merge(human_part, mouse_part, on="MGI", how="left")
merged_hum_mouse = merged_hum_mouse\
    .drop(['Unnamed: 0.1', 'Unnamed: 0_x', 'MP_x', 'Unnamed: 0_y'], axis=1)\
    .rename(columns={"MP_y": "MP"})

In [18]:
merged_hum_mouse.to_csv("db_4_entrez_hp_mgi_mp.tsv", sep='\t')