In [1]:
import pandas as pd

In [17]:
human_mouse_genes = pd.read_csv("../databases/HMD_HumanPhenotype.rpt", delimiter="\t", header=None)\
    .rename(columns={0: "gene_human", 1: "entrez_id_human", 2: "gene_mouse", 3: "MGI", 4: "MP"})

In [21]:
human_mouse_genes.MP.notna().sum()

13634

In [3]:
human_mouse_genes = human_mouse_genes.drop(['MP', 5], axis=1)

In [4]:
human_mouse_genes

      gene_human  entrez_id_human gene_mouse          MGI
0           A1BG                1       A1bg  MGI:2152878
1           A1CF            29974       A1cf  MGI:1917115
2            A2M                2        A2m  MGI:2449119
3        A3GALT2           127550    A3galt2  MGI:2685279
4         A4GALT            53947     A4galt  MGI:3512453
...          ...              ...        ...          ...
29681     ZYG11A           440590     Zyg11a  MGI:2446208
29682     ZYG11B            79699     Zyg11b  MGI:2685277
29683        ZYX             7791        Zyx   MGI:103072
29684      ZZEF1            23140      Zzef1  MGI:2444286
29685       ZZZ3            26009       Zzz3  MGI:1920453

[29686 rows x 4 columns]

In [5]:
mouse_gene_phenotype = pd.read_csv("../databases/MGI_Geno_DiseaseDO.rpt.txt", delimiter="\t", header=None)

In [6]:
mouse_gene_phenotype = mouse_gene_phenotype.drop([0, 1, 2, 3, 5, 7, 8], axis=1).rename(columns={4: "MP", 6: "MGI"})

In [7]:
mouse_gene_phenotype

               MP          MGI
0      MP:0002127   MGI:105923
1      MP:0000452   MGI:105923
2      MP:0002108   MGI:105923
3      MP:0000614   MGI:105923
4      MP:0001823   MGI:105923
...           ...          ...
38224  MP:0001925  MGI:1914311
38225  MP:0002687  MGI:1914311
38226  MP:0002675  MGI:1914311
38227  MP:0005578  MGI:1914311
38228  MP:0008545  MGI:1914311

[38229 rows x 2 columns]

In [8]:
mouse_g_to_p_wide = mouse_gene_phenotype.groupby("MGI").agg({"MP": lambda x: list(x)})

In [16]:
mouse_g_to_p_wide

                                                           MP
MGI
MGI:101762  [MP:0001544, MP:0000249, MP:0002083, MP:000195...
MGI:101764  [MP:0002064, MP:0002083, MP:0001399, MP:000218...
MGI:101773  [MP:0002269, MP:0000755, MP:0000754, MP:000092...
MGI:101864  [MP:0001513, MP:0000752, MP:0001053, MP:000940...
MGI:101884  [MP:0000747, MP:0000063, MP:0005293, MP:000541...
...                                                       ...
MGI:99918   [MP:0002066, MP:0002064, MP:0001360, MP:000136...
MGI:99919   [MP:0001363, MP:0000316, MP:0000433, MP:000126...
MGI:99928   [MP:0002401, MP:0001823, MP:0002444, MP:000214...
MGI:99953   [MP:0010254, MP:0010254, MP:0002092, MP:000128...
MGI:99954   [MP:0001544, MP:0002083, MP:0000266, MP:000126...

[1550 rows x 1 columns]

In [9]:
with_MP_long = pd.merge(human_mouse_genes, mouse_gene_phenotype, how='left', on = 'MGI').drop_duplicates()

In [10]:
with_MP_wide = pd.merge(human_mouse_genes, mouse_g_to_p_wide, how='left', on = 'MGI')

In [11]:
with_MP_wide.head()

  gene_human  entrez_id_human gene_mouse          MGI   MP
0       A1BG                1       A1bg  MGI:2152878  NaN
1       A1CF            29974       A1cf  MGI:1917115  NaN
2        A2M                2        A2m  MGI:2449119  NaN
3    A3GALT2           127550    A3galt2  MGI:2685279  NaN
4     A4GALT            53947     A4galt  MGI:3512453  NaN

In [12]:
with_MP_wide.MP.notna().sum()

1485

In [15]:
with_MP_wide.to_csv("current_no_human.csv", sep='\t')

In [13]:
mouse_human_gene_phenotype = pd.read_csv("../databases/MGI_DO.rpt.txt", delimiter="\t")

In [14]:
mouse_human_gene_phenotype

,DO Disease ID,DO Disease Name,OMIM IDs,Common Organism Name,NCBI Taxon ID,Symbol,EntrezGene ID,Mouse MGI ID
0,DOID:0112248,17-beta hydroxysteroid dehydrogenase 3 deficiency,OMIM:264300,human,9606,HSD17B3,3293.0,NaN
1,DOID:0112248,17-beta hydroxysteroid dehydrogenase 3 deficiency,OMIM:264300,"mouse, laboratory",10090,Hsd17b3,15487.0,MGI:107177
2,DOID:0111453,2-aminoadipic 2-oxoadipic aciduria,OMIM:204750,human,9606,DHTKD1,55526.0,NaN
3,DOID:0111453,2-aminoadipic 2-oxoadipic aciduria,OMIM:204750,"mouse, laboratory",10090,Dhtkd1,209692.0,MGI:2445096
4,DOID:0050573,2-hydroxyglutaric aciduria,NaN,human,9606,SLC25A1,6576.0,NaN
...,...,...,...,...,...,...,...,...
17993,DOID:905,Zellweger syndrome,NaN,human,9606,ABCD3,5825.0,NaN
17994,DOID:905,Zellweger syndrome,NaN,"mouse, laboratory",10090,Pex1,71382.0,MGI:1918632
17995,DOID:905,Zellweger syndrome,NaN,"mouse, laboratory",10090,Pex11b,18632.0,MGI:1338882
17996,DOID:0060478,Zika fever,NaN,human,9606,STAT2,6773.0,NaN
17997,DOID:0050782,Zollinger-Ellison syndrome,NaN,human,9606,EGF,1950.0,NaN